### PR TITLE
Polymer 1.0 compatibility

### PR DESCRIPTION
**Pull request by hadfieldn**
also adds support for expired event and tabindex attribute

### CODE REVIEW

**Comment by cbalit** [comment]
Nice work @hadfielden. I will check the unit test on monday. Can you make the PR on my repo?https://github.com/cbalit/re-captcha
Thanks

**Comment by hadfieldn** [comment]
@cbalit Just submitted the PR -- hope that's what you were expecting. Thanks!

**Comment by cbalit** [comment]
@hadfieldn, i just merge your PR into my repository and everything work fine. I just rename the component (my element is re-captcha), fixed the unit test and add somme change i was working on. Thank you

**Comment by cbalit** [comment]
@addyosmani i think you can merge this PR. It will also fix the issue #5

**Comment by hadfieldn** [comment]
@cbalit Great, thanks for the update -- glad there weren't any issues.

**Comment by addyosmani** [comment]
@atotic Would you like to take a look over this one too just to make sure you're happy with it before we go ahead with a merge?

@cbalit thanks for the ping!

**Comment by atotic** [comment]
.bowerrc should be removed (just blew away my tree)
(the new development style bower installs locally, and we developers use polyserve to test)

add .gitignore like this one: https://github.com/GoogleWebComponents/google-map/blob/master/.gitignore

Optional: 
Move demo to demo/index.html, and patch @demo tag.
jsdoc @attribute, @type, @default, @method are no longer required, we infer them from code.

I was unable to see audio in demo, although correct argument was being passed to render. Probably some fancy api2 thing, where it knows I do not need audio...

**Comment by atotic** [comment]
@addyosmani or they can just merge, and I can do these patches. I have them in my tree already, could not test without it...

**Comment by hadfieldn** [comment]
@atotic @addyosmani I just pushed the changes you described, and also fixed the tests.

**Comment by atotic** [comment]
LGTM, still can't hear see audio no idea why.

**Comment by hadfieldn** [comment]
Hmm.. strange. The audio works for me.

**Comment by addyosmani** [comment]
LGTM2. Landing shortly.

**Pull request closed without merging**
